version: "3.5"

#services:
#  app:
#    build: .
#    restart: unless-stopped
#    environment:
#      - BOT_WEBHOOK_URL=${BOT_WEBHOOK_URL:?err}
#      - BOT_HOST=${BOT_HOST:?err}
#      - BOT_PORT=${BOT_PORT:?err}
#      - BOT_ADMIN_CHAT=${BOT_ADMIN_CHAT:?err}
#      - BOT_API_TOKEN_BOT=${BOT_API_TOKEN_BOT:?err}
#      - BOT_DEBUG=${BOT_DEBUG:?err}
#      - BOT_SENTRY_DSN=${BOT_SENTRY_DSN:?err}
#    volumes:
#       - ./db:/db
#       - .logs:/logs
#    ports:
#      - "${BOT_PORT:-80:88}:${BOT_PORT}"


services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
       - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/